apiVersion: v1
kind: Pod
metadata:
  name: pod-checkmk
  labels:
    env: dev
spec:
  containers:
  - name: container-checkmk
    image: smilewonjin/checkmk:2.1.0p29-001
    ports:
    - containerPort: 80
      protocol: TCP
